apiVersion: carto.run/v1alpha1
kind: Deliverable
metadata:
  labels:
    app.kubernetes.io/component: deliverable
    app.kubernetes.io/part-of: hello-world
    app.tanzu.vmware.com/deliverable-type: web
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    carto.run/cluster-template-name: deliverable-template
    carto.run/resource-name: deliverable
    carto.run/supply-chain-name: source-test-scan-to-url
    carto.run/template-kind: ClusterTemplate
    carto.run/template-lifecycle: mutable
    carto.run/workload-name: hello-world
    carto.run/workload-namespace: workloads
  name: hello-world
  namespace: workloads
spec:
  params:
  - name: gitops_ssh_secret
    value: http-git-secret
  source:
    git:
      ref:
        branch: main
      url: https://github.com/vmware-tanzu-labs/hkjc-workloads-gitops.git
    subPath: config/workloads/hello-world