apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: hello-world.app
  namespace: workloads
spec:
  serviceAccountName: default
  fetch:
  - git:
      url: https://github.com/justeh/tap-gitops
      ref: main
      subPath: config
  template:
  - ytt: {}
  deploy: 
  - kapp: {}
