apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: hello-world
  namespace: workloads
  annotations:
    kapp.k14s.io/update-strategy: always-replace
spec:
  serviceAccountName: default
  fetch:
  - git:
      url: https://github.com/justeh/tap-gitops
      ref: origin/main
      subPath: config/workloads/hello-world
  template:
  - ytt: {}
  deploy: 
  - kapp: {}
