apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: hello-world
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: hello-world
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  env:
  - name: APP_MESSAGE
    value: World
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  # - name: gitops_server_address
  #   value: https://github.com/
  # - name: gitops_repository_owner
  #   value: justeh
  # - name: gitops_repository_name
  #   value: tap-gitops
  source:
    git:
      url: https://github.com/justeh/hello-world
      ref:
        tag: v1.1.0
