apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: log4j-world
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: log4j-world
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  env:
  - name: APP_MESSAGE
    value: World
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/justeh/hello-world
      ref:
        branch: log4j
